"use client";
import { BASKET, TOKENS, type TokenSymbol } from "@/constants/tokens";
import { useAccount } from "wagmi";
import { ArrowUpRight, Blocks, Coins, Gauge, Orbit, Wallet } from "lucide-react";
import { TokenIcon } from "../ui/TokenIcon";
import { usePortfolioBalances } from "@/hooks/usePortfolioBalances";
import { usePreferences } from "../providers/PreferencesProvider";

export function PortfolioPage({ onTrade }: { onTrade: () => void }) {
  const { isConnected } = useAccount();
  const { t } = usePreferences();
  const { balances, nativeBalance } = usePortfolioBalances();
  if (!isConnected) return <div className="enter grid min-h-[68vh] place-items-center"><section className="relative w-full max-w-4xl overflow-hidden rounded-[28px] border border-[var(--line)] bg-[linear-gradient(135deg,var(--hero-from),var(--hero-to))] p-7 shadow-[0_28px_100px_rgba(0,0,0,.22)] sm:p-12"><div className="data-grid absolute inset-y-0 right-0 w-1/2 opacity-35"/><div className="absolute right-[-5rem] top-[-5rem] h-64 w-64 rounded-full border border-[var(--line-strong)]"/><div className="relative max-w-2xl"><span className="neo-kicker">Institutional DeFi Infrastructure</span><h1 className="mt-7 font-display text-4xl font-bold leading-[1.02] sm:text-6xl">{t("portfolio.hero1")}<br/><span className="text-[var(--neo)]">{t("portfolio.hero2")}</span></h1><p className="mt-6 max-w-[54ch] text-base leading-8 text-[var(--muted)] sm:text-lg">{t("portfolio.heroText")}</p><div className="mt-9 grid gap-3 sm:grid-cols-3">{[{icon:Wallet,label:t("portfolio.connect"),value:t("portfolio.connectValue")},{icon:Blocks,label:t("portfolio.contracts"),value:t("portfolio.contractsValue")},{icon:Orbit,label:t("portfolio.custody"),value:t("portfolio.custodyValue")}].map(({icon:Icon,label,value})=><div key={label} className="rounded-xl border border-[var(--line)] bg-[var(--hover)] p-4"><Icon size={17} className="text-[var(--neo)]"/><p className="mt-3 text-sm font-bold">{label}</p><p className="mt-1 text-xs text-[var(--muted)]">{value}</p></div>)}</div></div></section></div>;
  const assets: TokenSymbol[] = ["NETF", "NETH", "NBTC", "LINK", "USDC"];
  const value = (amount: string) => amount === "--" ? <span className="skeleton" aria-label={t("portfolio.loading")}>000.0000</span> : amount;
  return <div className="enter space-y-7">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="neo-kicker">Connected Portfolio</span><h1 className="mt-4 font-display text-3xl font-bold sm:text-4xl">{t("portfolio.console")}</h1><p className="mt-2 text-base text-[var(--muted)]">{t("portfolio.subtitle")}</p></div><button onClick={onTrade} className="neo-button flex min-h-12 items-center justify-center gap-2 rounded-xl px-5 text-sm font-extrabold">{t("portfolio.trade")} <ArrowUpRight size={17}/></button></div>
    <section className="grid gap-5 xl:grid-cols-[1.5fr_.8fr]">
      <div className="grid gap-5 sm:grid-cols-2">
        <article className="panel relative overflow-hidden p-6"><div className="absolute right-[-2rem] top-[-2rem] h-28 w-28 rounded-full border border-[var(--line)]"/><p className="flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[var(--muted)]"><Coins size={16} className="text-[var(--neo)]"/>{t("portfolio.gas")}</p><strong className="metric-value mt-8 block min-h-10 text-4xl">{value(nativeBalance)}</strong><span className="mt-3 block text-sm text-[var(--muted)]">{t("portfolio.gasHelp")}</span></article>
        <article className="panel relative overflow-hidden border-[var(--line-strong)] p-6"><div className="absolute inset-x-0 top-0 h-px bg-[linear-gradient(90deg,transparent,var(--neo),transparent)]"/><p className="flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[var(--neo)]"><Wallet size={16}/>{t("portfolio.position")}</p><strong className="metric-value mt-8 block min-h-10 text-4xl">{value(balances.NETF)}</strong><span className="mt-3 block text-sm text-[var(--muted)]">{t("portfolio.positionHelp")}</span></article>
      </div>
      <article className="panel flex items-center gap-6 p-6"><div className="relative grid h-28 w-28 shrink-0 place-items-center rounded-full" style={{background:"conic-gradient(#f59e0b 0 40%, #6478ef 40% 70%, #2855d9 70% 80%, #2775ca 80% 100%)"}}><div className="grid h-20 w-20 place-items-center rounded-full bg-[var(--surface)]"><div className="text-center"><Gauge size={18} className="mx-auto text-[var(--neo)]"/><span className="mt-1 block font-mono text-[9px] text-[var(--muted)]">4 ASSETS</span></div></div></div><div className="min-w-0 flex-1"><p className="font-display text-lg font-bold">{t("portfolio.allocation")}</p><div className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3">{BASKET.map(item => <span className="flex items-center gap-2 text-xs font-semibold" key={item.symbol}><i aria-hidden="true" className="h-2 w-2 rounded-full" style={{background:TOKENS[item.symbol].color}}/>{item.symbol}<span className="ml-auto text-[var(--muted)]">{item.weight}%</span></span>)}</div></div></article>
    </section>
    <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--line)] px-5 py-5 sm:px-6"><div><p className="neo-kicker">Wallet Inventory</p><h2 className="mt-3 font-display text-xl font-bold">{t("portfolio.inventory")}</h2></div><span className="font-mono text-[9px] uppercase tracking-[.15em] text-[var(--muted)]">Live · ERC-20</span></div>
      <div className="grid md:grid-cols-2 xl:grid-cols-3">{assets.map((symbol,index) => <div key={symbol} className={`flex items-center gap-4 border-[var(--line)] px-5 py-5 sm:px-6 ${index < assets.length - 1 ? "border-b" : ""} md:border-b md:[&:nth-child(odd)]:border-r xl:[&:nth-child(odd)]:border-r-0 xl:[&:not(:nth-child(3n))]:border-r`}><TokenIcon symbol={symbol} size={42}/><div><p className="font-bold">{symbol}</p><p className="text-xs text-[var(--muted)]">{TOKENS[symbol].name}</p></div><strong className="metric-value ml-auto min-w-[8ch] text-right text-lg">{value(balances[symbol])}</strong></div>)}</div>
    </section>
  </div>;
}
